@host = localhost:8000

@name = "health"
POST http://{{host}}/proto.api.v1.HealthService/Check
Content-Type: application/json

{
    
}
###

@name = "login"
POST http://{{host}}/auth/login/
Content-Type: application/json

{
    "email": "test@email.com",
    "password": "Frozen11"
}

###
@name = "signup
POST http://{{host}}/auth/signup/
Content-Type: application/json

{
    "email": "test@email.com",
    "password1": "Frozen11",
    "password2": "Frozen11"
}

###
@name = "logout"
POST http://{{host}}/auth/logout/
Content-Type: application/json


###
@name = "me"
POST http://{{host}}/proto.api.v1.ProtectedAuthService/Me
Content-Type: application/json

{
    
}